### ISSUE TITLE
fileUrl传file对象报错，还有为什么控制台这么多警告

### ISSUE THREAD

**Issue by wucyAAA** [zyl-ui/vue-file-viewer#1]
报错：
vue.runtime.esm.js:619 [Vue warn]: Invalid prop: type check failed for prop "fileUrl". Expected String, Object, got File 
警告：
index.js:97 DOCX: Unknown document element: trPr.wAfter
index.js:97 DOCX: Unknown document element: trPr.wBefore

**Comment by SuperAiopr** [comment]
因为参数要的是String，只能是本地地址或者网络地址，你传个对象肯定报错啊

**Comment by wucyAAA** [comment]
好久了，最后没有用这个库，感谢大哥回复

**Comment by abu3389** [comment]
> 报错： vue.runtime.esm.js:619 [Vue warn]: Invalid prop: type check failed for prop "fileUrl". Expected String, Object, got File 警告： index.js:97 DOCX: Unknown document element: trPr.wAfter index.js:97 DOCX: Unknown document element: trPr.wBefore

https://file-viewer.yiwowang.com/#/start
参考：接收blob二进制文件流消息示例
